name: Upload Captain Artifact
description: Upload artifacts to Captain
author: RWX
branding:
  icon: 'upload-cloud'
  color: 'green'
inputs:
  artifacts:
    required: true
    description: |
      this is a json array of objects with fields...
      - name: how the artifact will be shown in captain
      - path: path to test result. This field supports bash globbing (e.g. **/*).
      - kind: for now, this should always be "test_results"
      - parser: one of
        - cypress_junit_xml
        - jest_json
        - junit_xml
        - rspec_json
        - xunit_dot_net_xml
  if-files-not-found:
    required: false
    default: warn
    description: |
      The behavior of the action when an artifact's file is not found.

      Options:
        - ignore: Output neither a warning nor an error; the action will succeed.
        - warn (default): Output a warning; the action will succeed.
        - error: Output an error; the action will fail.
  job-name:
    required: false
    description: >
      This is required if you set the `name` property on your job.
      If you provided a name, set that same value here.
  job-matrix:
    required: false

  captain-token:
    required: true

  captain-base-url:
    required: false
    default: https://captain.build
runs:
  using: 'node16'
  main: 'dist/index.js'
