name: Upload Vanguard Artifact
description: Upload artifacts to Vanguard
author: RWX
inputs:
  artifacts:
    required: true
  if-files-not-found:
    required: false
    default: warn
    description: |
      The behavior of the action when an artifact's file is not found.

      Options:
        - ignore: Output neither a warning nor an error; the action will succeed.
        - warn (default): Output a warning; the action will succeed.
        - error: Output an error; the action will fail.
  job-name:
    required: false
    description: >
      This is required if you set the `name` property on your job.
      If you provided a name, set that same value here.
  job-matrix:
    required: true
  vanguard-token:
    required: true
  vanguard-base-url:
    required: false
    default: https://vanguard.rwx.com
runs:
  using: 'node16'
  main: 'dist/index.js'
